name: Process Scheduled Messages

on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-messages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Scheduled Messages
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/process-scheduled-messages" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
        continue-on-error: true

      - name: Log Result
        if: always()
        run: echo "Scheduled message processing completed at $(date)"
